---
# tasks file for jenkins
- name: Download Java JRE
  get_url:
    url: http://download.oracle.com/otn-pub/java/jdk/8u60-b27/jre-8u60-linux-x64.rpm
    dest: /opt/jre-8u60-linux-x64.rpm
    headers: 'Cookie: gpw_e24=http%3%2F%2Fwww.oracle.com%2F;oraclelicense=accept-securebackup-cookie'
    
- name: install Java JRE rpm from a local file
  yum:
    name: /opt/jre-8u60-linux-x64.rpm
    state: present
    
- name: Download Java JDK
  get_url:
    url: http://download.oracle.com/otn-pub/java/jdk/8u60-b27/jdk-8u60-linux-x64.rpm
    dest: /opt/jdk-8u60-linux-x64.rpm
    headers: 'Cookie: gpw_e24=http%3%2F%2Fwww.oracle.com%2F;oraclelicense=accept-securebackup-cookie'
    
- name: Install Java JDK rpm from a local file
  yum:
    name: /opt/jdk-8u60-linux-x64.rpm
    state: present

- name: Import Jenkins GPG key
  rpm_key:
    state: present
    key: http://pkg.jenkins-ci.org/redhat/jenkins-ci.org.key

- name: Add Jenkins repository
  yum_repository:
    name: jenkins
    description: jenkins repository
    baseurl: http://pkg.jenkins.io/redhat
    enabled: no
    gpgcheck: yes

- name: Install Jenkins
  yum:
    name: jenkins
    enablerepo: jenkins
    state: present

- name: Start Jenkins
  service:
    name: jenkins-2.45
    enabled: yes
    state: started
